### PR TITLE
Add French Translation

### PR DESCRIPTION
**Pull request by 11jo**
Hello,

Here the French translation of The Boareskyr Bridge Scene, Proofreading by Mera !

Added french entries to tp2, I hope it's ok.

Thanks a lot for this new mod !

(Themedtweak from lauriel, RoadToDiscovery, AnotherFineHell, JasteyTweak and The Boareskyr Bridge Scene are really good additions,)

### CODE REVIEW

**Comment by Gitjas** [comment]
Great, thank you! What do I put into the credits, translated by 11jo and proofread by Mera or would you prefer another name?
Thanks for the kind words!

**Comment by 11jo** [comment]
Sorry I didn't mention that 11jo is JohnBob ! 

Thanks !

**Comment by Gitjas** [comment]
Ah, alright! Thank you!

**Comment by Gitjas** [comment]
New version is up! Thanks again!

**Pull request merged**
